baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Chaos Blog'
theme = 'PaperMod'

[params]
  math = true
  defaultTheme = "auto"
  disableSpecial1stPost = true

# 下面是为你定制的 Markdown 和公式渲染保护规则
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
