baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Chaos Blog'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON æ˜¯å¼€å¯æœç´¢çš„å…³é”®

[params]
  math = true
  defaultTheme = "auto"
  disableSpecial1stPost = true

# ä¸‹é¢æ˜¯ä¸ºä½ å®šåˆ¶çš„ Markdown å’Œå…¬å¼æ¸²æŸ“ä¿æŠ¤è§„åˆ™
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[menu]
  [[menu.main]]
    identifier = "search"
    name = "ğŸ” æœç´¢"
    url = "/search/"
    weight = 10

  [[menu.main]]
    identifier = "archive"
    name = "ğŸ—„ï¸ å½’æ¡£"
    url = "/archive/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "ğŸ—‚ï¸ åˆ†ç±»"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "ğŸ·ï¸ æ ‡ç­¾"
    url = "/tags/"
    weight = 40
